[package]
name = "planets_sim"
version = "0.1.0"
authors = ["Mayghal <mayghalvijapura@live.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


